export enum TodosActionTypes{
    ADD_TODO = "ADD_TODO",
    EDIT_TODO = "EDIT_TODO",
    DELETE_TODO = "DELETE_TODO",
    CHANGE_COMPLETED = "CHANGE_COMPLETED",
    ADD_LOGIN = "ADD_LOGIN",
    CHANGE_SELECTED_TODOS = "CHANGE_SELECTED_TODOS",
}